//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busidex.Api.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public Card()
        {
            this.ExternalLinks = new HashSet<ExternalLink>();
        }
    
        public long CardId { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public byte[] FrontImage { get; set; }
        public string FrontType { get; set; }
        public string FrontOrientation { get; set; }
        public byte[] BackImage { get; set; }
        public string BackType { get; set; }
        public string BackOrientation { get; set; }
        public Nullable<int> BusinessId { get; set; }
        public bool Searchable { get; set; }
        public string CompanyName { get; set; }
        public string Email { get; set; }
        public string Url { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> OwnerId { get; set; }
        public Nullable<System.Guid> OwnerToken { get; set; }
        public System.DateTime Updated { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.Guid> FrontFileId { get; set; }
        public Nullable<System.Guid> BackFileId { get; set; }
        public string DisplayType { get; set; }
        public string Markup { get; set; }
        public byte Visibility { get; set; }
        public int CardTypeId { get; set; }
        public string SEO_Name { get; set; }
        public string CustomContent { get; set; }
    
        public virtual ICollection<ExternalLink> ExternalLinks { get; set; }
    }
}
