//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busidex.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BusidexContent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusidexContent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Busidex.Resources.BusidexContent", typeof(BusidexContent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unexpected problem creating your account.
        /// </summary>
        internal static string Error_CreatingAccount {
            get {
                return ResourceManager.GetString("Error_CreatingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect.
        /// </summary>
        internal static string Error_IncorrectUserNameOrPassword {
            get {
                return ResourceManager.GetString("Error_IncorrectUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to get your card into the mix? Add it to our collection and get found. Looking to organize your collection? Add it to your personal &apos;My Busidex&apos; collection..
        /// </summary>
        internal static string HomeAddACard {
            get {
                return ResourceManager.GetString("HomeAddACard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search our huge collection of business cards to quickly find the one you need. Find one you really like? Add it to your personal &apos;My Busidex&apos; collection..
        /// </summary>
        internal static string HomeFindACard {
            get {
                return ResourceManager.GetString("HomeFindACard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busi-dex is the business card place.&lt;br /&gt;Got a pile of cards? &lt;a href=&quot;../Busidex/Mine&quot;&gt;Keep them here&lt;/a&gt;, get them from anywhere.&lt;br /&gt;Got a business? Get your card in the mix and in front of everyone.
        ///&lt;br /&gt;Looking for a card? Find it here..
        /// </summary>
        internal static string HomeMissionStatement {
            get {
                return ResourceManager.GetString("HomeMissionStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your collection of cards. You can organize them based on category, share them, and link them together. No more looking through your wallet, under the couch, under the desk, or wherever you tend to lose your stuff (like that never happens)..
        /// </summary>
        internal static string HomeMyBusidex {
            get {
                return ResourceManager.GetString("HomeMyBusidex", resourceCulture);
            }
        }
    }
}
