//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busidex.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardAddress
    {
        public long CardAddressId { get; set; }
        public long CardId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public bool Deleted { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeoLocation { get; set; }
    }
}
