//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busidex.Providers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BusidexContent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusidexContent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Busidex.Providers.BusidexContent", typeof(BusidexContent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must indicate if you are the owner of this card or not..
        /// </summary>
        internal static string Error_Card_IndicateOwner {
            get {
                return ResourceManager.GetString("Error_Card_IndicateOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This card already has an owner.
        /// </summary>
        internal static string Error_Card_Owned {
            get {
                return ResourceManager.GetString("Error_Card_Owned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select a card image.
        /// </summary>
        internal static string Error_Card_SelectCardImage {
            get {
                return ResourceManager.GetString("Error_Card_SelectCardImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unexpected problem creating your account.
        /// </summary>
        internal static string Error_CreatingAccount {
            get {
                return ResourceManager.GetString("Error_CreatingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems your account is not yet active. Please check your email for the confirmation we sent you when you registered. It may possibly have been picked up by a spam filter..
        /// </summary>
        internal static string Error_InactiveAccount {
            get {
                return ResourceManager.GetString("Error_InactiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect.
        /// </summary>
        internal static string Error_IncorrectUserNameOrPassword {
            get {
                return ResourceManager.GetString("Error_IncorrectUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to get your card into the mix? Add it to Busidex and get found. Looking to organize your cards? Add it to your personal &apos;My Busidex&apos; collection..
        /// </summary>
        internal static string HomeAddACard {
            get {
                return ResourceManager.GetString("HomeAddACard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Busidex is the business card place&lt;/strong&gt; where it&apos;s all about staying current and staying connected. Your business card never had so much power as it does with Busidex..
        /// </summary>
        internal static string HomeElevatorPitch {
            get {
                return ResourceManager.GetString("HomeElevatorPitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search our huge collection of business cards to quickly find the one you need. Find one you really like? Add it to your personal &apos;My Busidex&apos; collection..
        /// </summary>
        internal static string HomeFindACard {
            get {
                return ResourceManager.GetString("HomeFindACard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busidex is the business card place.&lt;br /&gt;Got a pile of cards? &lt;a href=&quot;../Busidex/Mine&quot;&gt;Keep them here&lt;/a&gt;, get them from anywhere.&lt;br /&gt;Got a business? &lt;a href=&quot;../Card/Add&quot;&gt;Get your card in the mix&lt;/a&gt; and start building your network.
        ///&lt;br /&gt;Looking for a card? &lt;a href=&quot;../Card/Search&quot;&gt;Find it here&lt;/a&gt;..
        /// </summary>
        internal static string HomeMissionStatement {
            get {
                return ResourceManager.GetString("HomeMissionStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your collection of cards. You can organize them, share them, and link them together..
        /// </summary>
        internal static string HomeMyBusidex {
            get {
                return ResourceManager.GetString("HomeMyBusidex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize, arrange and re-arrange your contacts into groups for quick reference..
        /// </summary>
        internal static string HomeMyBusiGroups {
            get {
                return ResourceManager.GetString("HomeMyBusiGroups", resourceCulture);
            }
        }
    }
}
