
var services = services || angular.module('busidexstartApp.services', ['ngResource']);
services
    .factory('StateCodes', function () {
        'use strict';
        return [
            {
                StateCodeId: 1,
                Code: 'AL',
                Name: 'Alabama'
            }, {
                StateCodeId: 2,
                Code: 'AK',
                Name: 'Alaska'
            }, {
                StateCodeId: 3,
                Code: 'AZ',
                Name: 'Arizona'
            }, {
                StateCodeId: 4,
                Code: 'AR',
                Name: 'Arkansas'
            }, {
                StateCodeId: 5,
                Code: 'CA',
                Name: 'California'
            }, {
                StateCodeId: 6,
                Code: 'CO',
                Name: 'Colorado'
            }, {
                StateCodeId: 7,
                Code: 'CT',
                Name: 'Connecticut'
            }, {
                StateCodeId: 8,
                Code: 'DE',
                Name: 'Delaware'
            }, {
                StateCodeId: 9,
                Code: 'DC',
                Name: 'District Of Columbia'
            }, {
                StateCodeId: 10,
                Code: 'FL',
                Name: 'Florida'
            }, {
                StateCodeId: 11,
                Code: 'GA',
                Name: 'Georgia'
            }, {
                StateCodeId: 12,
                Code: 'HI',
                Name: 'Hawaii'
            }, {
                StateCodeId: 13,
                Code: 'ID',
                Name: 'Idaho'
            }, {
                StateCodeId: 14,
                Code: 'IL',
                Name: 'Illinois'
            }, {
                StateCodeId: 15,
                Code: 'IN',
                Name: 'Indiana'
            }, {
                StateCodeId: 16,
                Code: 'IA',
                Name: 'Iowa'
            }, {
                StateCodeId: 17,
                Code: 'KS',
                Name: 'Kansas'
            }, {
                StateCodeId: 18,
                Code: 'KY',
                Name: 'Kentucky'
            }, {
                StateCodeId: 19,
                Code: 'LA',
                Name: 'Louisiana'
            }, {
                StateCodeId: 20,
                Code: 'ME',
                Name: 'Maine'
            }, {
                StateCodeId: 21,
                Code: 'MD',
                Name: 'Maryland'
            }, {
                StateCodeId: 22,
                Code: 'MA',
                Name: 'Massachusetts'
            }, {
                StateCodeId: 23,
                Code: 'MI',
                Name: 'Michigan'
            }, {
                StateCodeId: 24,
                Code: 'MN',
                Name: 'Minnesota'
            }, {
                StateCodeId: 25,
                Code: 'MS',
                Name: 'Mississippi'
            }, {
                StateCodeId: 26,
                Code: 'MO',
                Name: 'Missouri'
            }, {
                StateCodeId: 27,
                Code: 'MT',
                Name: 'Montana'
            }, {
                StateCodeId: 28,
                Code: 'NE',
                Name: 'Nebraska'
            }, {
                StateCodeId: 29,
                Code: 'NV',
                Name: 'Nevada'
            }, {
                StateCodeId: 30,
                Code: 'NH',
                Name: 'New Hampshire'
            }, {
                StateCodeId: 31,
                Code: 'NJ',
                Name: 'New Jersey'
            }, {
                StateCodeId: 32,
                Code: 'NM',
                Name: 'New Mexico'
            }, {
                StateCodeId: 33,
                Code: 'NY',
                Name: 'New York'
            }, {
                StateCodeId: 34,
                Code: 'NC',
                Name: 'North Carolina',
            }, {
                StateCodeId: 35,
                Code: 'ND',
                Name: 'North Dakota'
            }, {
                StateCodeId: 36,
                Code: 'OH',
                Name: 'Ohio'
            }, {
                StateCodeId: 37,
                Code: 'OK',
                Name: 'Oklahoma'
            }, {
                StateCodeId: 38,
                Code: 'OR',
                Name: 'Oregon'
            }, {
                StateCodeId: 39,
                Code: 'PA',
                Name: 'Pennsylvania'
            }, {
                StateCodeId: 40,
                Code: 'RI',
                Name: 'Rhode Island'
            }, {
                StateCodeId: 41,
                Code: 'SC',
                Name: 'South Carolina'
            }, {
                StateCodeId: 42,
                Code: 'SD',
                Name: 'South Dakota'
            }, {
                StateCodeId: 43,
                Code: 'TN',
                Name: 'Tennessee'
            }, {
                StateCodeId: 44,
                Code: 'TX',
                Name: 'Texas'
            }, {
                StateCodeId: 45,
                Code: 'UT',
                Name: 'Utah'
            }, {
                StateCodeId: 46,
                Code: 'VT',
                Name: 'Vermont'
            }, {
                StateCodeId: 47,
                Code: 'VA',
                Name: 'Virginia'
            }, {
                StateCodeId: 48,
                Code: 'WA',
                Name: 'Washington'
            }, {
                StateCodeId: 49,
                Code: 'WV',
                Name: 'West Virginia'
            }, {
                StateCodeId: 50,
                Code: 'WI',
                Name: 'Wisconsin'
            }, {
                StateCodeId: 51,
                Code: 'WY',
                Name: 'Wyoming'
            }
        ];
    });